/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DYNAMICRATIOPROCESS_H
#define DYNAMICRATIOPROCESS_H

/* function declarations */
void init_dynamicRatioProcess(void);
Netsnmp_Node_Handler handle_dynamicRatioProcessCpu;
Netsnmp_Node_Handler handle_dynamicRatioProcessMemory;

#endif /* DYNAMICRATIOPROCESS_H */
